#  Mountain Rescue Incident
This notebook consisted of some background analysis behind the web application on https://shiminc.github.io/mountain_rescue.html
- The app is aimed to raise readers' awareness about the times and efforts of mountain rescue team
- Therfore, there are interactive visualisation for readers to explore and the main content is written for general readers rather than research paper. 


## Research Questions
1. When do mountain rescue incidents most likely to occur across the years?
- Is it possible to predict the number of future incidents to assist in planning 
2. Is there any association between the month and the incident cause?
3. How much time and efforts are spent on mountain rescue?
 

## Data 
Web-scraping of [Wasdale Mountain Rescue](https://www.wmrt.org.uk/)
Incident reports since 1968, but patchy and inconsistent reporting until past 10 years. 
Therefore only 2015 - 2025 was used in the analysis. 

## Variables of interest
1. Count of incidents, 
2. Unit of analysis - month, year
3. Incident Cause 
4. hours, staff, staff-hours

## Limitation
1. Data: Potential investigation of variables affecting incident numbers and rescue time
- visitors number, social media, historical weather data 
2. Relative small dataset (1218 incidents)
- mainly descriptive analysis and non parametric analysis
- no separation of raw data and processed data, as it is relatively fast to process the raw data every time each analysis runs.

In [1]:
# import relevant libraries
import sys
from pathlib import Path
import pandas as pd

# import own modules
sys.path.append(str(Path.cwd().parent))
from utils.plot import create_stacked_bar_by_date, set_up_altair_jupyter
from utils.utils import preprocess_data, aggregate_by_year_month


from plotting.month_descriptive import boxplot_with_mean
from plotting.week_descriptive import aggregate_by_week_dayofweek
from plotting.histogram import histogram_for_overview

# import data
# TODO unpack when have time
data = preprocess_data()

# set up charts to be shown in jupyter notebooks
set_up_altair_jupyter()

         sum       mean  median  min   max       std
month
1       57.0   5.181818     5.0  1.0  11.0  3.188046
2       64.0   5.818182     6.0  1.0  13.0  4.261882
3       70.0   6.363636     6.0  0.0  13.0  4.177864
4       78.0   7.090909     7.0  0.0  15.0  4.928581
5      108.0   9.818182     7.0  2.0  24.0  7.305042
6      134.0  12.181818    10.0  4.0  20.0  6.258086
7      164.0  14.909091    17.0  3.0  25.0  7.231245
8      183.0  16.636364    18.0  8.0  25.0  4.500505
9      114.0  10.363636    11.0  2.0  17.0  4.780643
10     119.0  10.818182     9.0  5.0  27.0  6.645573
11      80.0   7.272727     7.0  3.0  15.0  3.523944
12      45.0   4.090909     3.0  0.0   8.0  2.625054
month  1   2   3   4   5   6   7   8   9   10  11  12
year
2015    5   1   2   2   8   7   3  12   7   9   3   3
2016    3   1   5   4   7  10   5  18   2   8   4   3
2017    2   8   6   5   7   4  16  18  17  19   7   0
2018    2   6   9   7   8   9   8  18   7   6   8   2
2019    5   3   2   3   5   7  17   8   6   5   7   2
2020    1   3   4   0   2   5  19  20   8   5   3   7
2021    6   1   0   7   4  20  11  16  17  27  15   8
2022   10  10  10   9   5  20  17  13  12  10   6   2
2023    6  13   8  15  24  18  25  16  11  10  10   6
2024   11  10  11  13  19  16  20  25  14  12  10   7
2025    6   8  13  13  19  18  23  19  13   8   7   5
finish
finish
finish

Examining the incident numbers in each month

In [2]:
create_stacked_bar_by_date(data, time='month').show()

JupyterChart(spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'data': {'name': 'da…

In [3]:
data_year_month = aggregate_by_year_month(data)
boxplot_with_mean(data_year_month).show()

JupyterChart(spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'layer': [{'mark': {…

In [4]:
# descriptive stats
data_year_month.groupby(by='month')['Incident'].agg(['sum','mean','median','min','max','std'])

         sum       mean  median  min   max       std
month
1       57.0   5.181818     5.0  1.0  11.0  3.188046
2       64.0   5.818182     6.0  1.0  13.0  4.261882
3       70.0   6.363636     6.0  0.0  13.0  4.177864
4       78.0   7.090909     7.0  0.0  15.0  4.928581
5      108.0   9.818182     7.0  2.0  24.0  7.305042
6      134.0  12.181818    10.0  4.0  20.0  6.258086
7      164.0  14.909091    17.0  3.0  25.0  7.231245
8      183.0  16.636364    18.0  8.0  25.0  4.500505
9      114.0  10.363636    11.0  2.0  17.0  4.780643
10     119.0  10.818182     9.0  5.0  27.0  6.645573
11      80.0   7.272727     7.0  3.0  15.0  3.523944
12      45.0   4.090909     3.0  0.0   8.0  2.625054

In [5]:
# each month numbers
pd.crosstab(data['year'],data['month'])

month  1   2   3   4   5   6   7   8   9   10  11  12
year
2015    5   1   2   2   8   7   3  12   7   9   3   3
2016    3   1   5   4   7  10   5  18   2   8   4   3
2017    2   8   6   5   7   4  16  18  17  19   7   0
2018    2   6   9   7   8   9   8  18   7   6   8   2
2019    5   3   2   3   5   7  17   8   6   5   7   2
2020    1   3   4   0   2   5  19  20   8   5   3   7
2021    6   1   0   7   4  20  11  16  17  27  15   8
2022   10  10  10   9   5  20  17  13  12  10   6   2
2023    6  13   8  15  24  18  25  16  11  10  10   6
2024   11  10  11  13  19  16  20  25  14  12  10   7
2025    6   8  13  13  19  18  23  19  13   8   7   5

In [ ]:
create_stacked_bar_by_date(data).show()

JupyterChart(spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'data': {'name': 'da…

In [2]:
#week
dayofweek = aggregate_by_week_dayofweek(data)
dayofweek

                       count    sum      mean  median  min  max       std
dayofweek dayofweek_n
0         Monday         572  123.0  0.215035     0.0  0.0  3.0  0.492591
1         Tuesday        572  136.0  0.237762     0.0  0.0  3.0  0.541879
2         Wednesday      572  132.0  0.230769     0.0  0.0  4.0  0.535170
3         Thursday       572  117.0  0.204545     0.0  0.0  3.0  0.468010
4         Friday         572  124.0  0.216783     0.0  0.0  4.0  0.490039
5         Saturday       572  343.0  0.599650     0.0  0.0  5.0  0.871137
6         Sunday         572  241.0  0.421329     0.0  0.0  3.0  0.724188

# Examining the seasonality of the mountain rescue incidents